const NEXT_SONG='skipnext';
const PREV_SONG='skipprev';
const CURRENT_SONG='current';
const SONGS_PLAYLIST='SONGS_PLAYLIST';
const ALBUM_PLAYLIST="ALBUM_PLAYLIST";
const SET_ISPLAYING="SET_ISPLAYING";
const SHUFFLE="SHUFFLE";
const SHOWPLAYER="SHOWPLAYER"

export {NEXT_SONG,PREV_SONG,CURRENT_SONG,SONGS_PLAYLIST,ALBUM_PLAYLIST,SET_ISPLAYING,SHUFFLE,SHOWPLAYER};